#!/usr/bin/env python3
"""Export Commander's launcher PNGs and SVG wrapper from the selected artwork."""

import base64
from pathlib import Path
import shutil
import subprocess


def main():
    root = Path(__file__).resolve().parent.parent
    branding = root / "crates/app/assets/branding"
    master = branding / "commander-icon-transparent.png"
    magick = shutil.which("magick")
    if magick is None:
        raise SystemExit("Install ImageMagick to export the app icon (magick).")
    # Resize from the smooth source while retaining its transparent background.
    for size, destination in (
        (1024, branding / "commander-icon.png"),
        (512, root / "packaging/org.example.Dualpane.png"),
    ):
        subprocess.run(
            [magick, str(master), "-filter", "Lanczos", "-resize", f"{size}x{size}",
             "-strip", str(destination)],
            check=True,
        )
    # Keep the existing GTK resource and Linux scalable-icon paths self-contained.
    artwork = base64.b64encode((branding / "commander-icon.png").read_bytes()).decode("ascii")
    (branding / "commander.svg").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by scripts/export-app-icon.py; edit commander-icon-transparent.png instead. -->\n'
        '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
        'width="1024" height="1024" viewBox="0 0 1024 1024">\n'
        '  <title>Commander</title>\n'
        '  <desc>A smooth blue and ice split face wearing a navy commander cap with gold chevrons, on a transparent background.</desc>\n'
        f'  <image width="1024" height="1024" xlink:href="data:image/png;base64,{artwork}"/>\n'
        '</svg>\n',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
